### ISSUE TITLE
New Repo for Radar Plugin

### ISSUE THREAD

**Issue by SyniRon** [RokasKil/DalamudPlugins#1]
I would like the new repo for the radar plugin please. I didn't see any other way to contact listed other than this.

**Comment by RokasKil** [comment]
Hi, when originally publishing the plugin in this repo I didn't consider how easy it would be to find it. I'm sorry to say that it was never meant to be public as the potential for misuse which I do not support is high. The "contact me" message was directed at my friends who I've personally given access to the plugin and there will be no further public versions of the plugin.

**Comment by SyniRon** [comment]
Ah, that is frustrating to hear as I had begun to rely on it for finding and reporting underground bots. I do understand your point of view though, thanks for letting me use it for a while anyway.
